<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\Expense;
use App\Models\PaperSize;
use App\Models\Service;
use App\Models\Transaction;
use App\Models\TransactionItem;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class BusinessDataSeeder extends Seeder
{
    private const TRANSACTION_NOTE = 'Generated by BusinessDataSeeder';

    private const EXPENSE_NOTE = 'Generated by BusinessDataSeeder';

    public function run(): void
    {
        $cashier = User::whereHas('role', fn ($query) => $query->where('name', 'kasir'))->first() ?? User::first();
        $services = Service::with('prices.paperSize')->get();
        $paperSizes = PaperSize::all()->keyBy('id');

        if (! $cashier) {
            $this->command->error('User belum tersedia. Jalankan UserSeeder terlebih dahulu.');

            return;
        }

        if ($services->isEmpty()) {
            $this->command->error('Layanan masih kosong. Jalankan ServiceSeeder terlebih dahulu.');

            return;
        }

        $customers = $this->prepareCustomers();

        $this->cleanupOldSeededData();

        $transactionProfiles = [
            ['count' => 18, 'status' => 'selesai', 'payment_status' => 'lunas'],
            ['count' => 8, 'status' => 'diambil', 'payment_status' => 'lunas'],
            ['count' => 9, 'status' => 'diproses', 'payment_status' => 'dp'],
            ['count' => 5, 'status' => 'selesai', 'payment_status' => 'dp'],
            ['count' => 10, 'status' => 'pending', 'payment_status' => 'belum_bayar'],
        ];

        $sequence = 1;

        foreach ($transactionProfiles as $profile) {
            for ($i = 0; $i < $profile['count']; $i++) {
                $transactionDate = $this->makeTransactionDate($sequence);
                $selectedServices = $services->random(rand(1, min(3, $services->count())));

                $this->createTransaction(
                    user: $cashier,
                    services: $selectedServices instanceof Collection ? $selectedServices : collect([$selectedServices]),
                    customer: $customers->random(),
                    paperSizes: $paperSizes,
                    status: $profile['status'],
                    paymentStatus: $profile['payment_status'],
                    transactionDate: $transactionDate,
                    sequence: $sequence,
                );

                $sequence++;
            }
        }

        $this->seedMonthlyExpenses($cashier);

        $this->command->info('BusinessDataSeeder berhasil: 50 transaksi bisnis dan pengeluaran bulan ini sudah dibuat.');
    }

    private function cleanupOldSeededData(): void
    {
        Expense::where('notes', self::EXPENSE_NOTE)->forceDelete();
        Transaction::where('notes', self::TRANSACTION_NOTE)->forceDelete();
    }

    private function prepareCustomers(): Collection
    {
        $defaults = [
            ['name' => 'Budi Santoso', 'phone' => '081210000001'],
            ['name' => 'Siti Rahma', 'phone' => '081210000002'],
            ['name' => 'Andi Pratama', 'phone' => '081210000003'],
            ['name' => 'Rina Marlina', 'phone' => '081210000004'],
            ['name' => 'Dewi Lestari', 'phone' => '081210000005'],
            ['name' => 'Agus Saputra', 'phone' => '081210000006'],
            ['name' => 'Maya Putri', 'phone' => '081210000007'],
            ['name' => 'Fajar Nugraha', 'phone' => '081210000008'],
            ['name' => 'Nadia Aulia', 'phone' => '081210000009'],
            ['name' => 'Toko Sinar Jaya', 'phone' => '081210000010'],
        ];

        foreach ($defaults as $customer) {
            Customer::firstOrCreate(
                ['phone' => $customer['phone']],
                [
                    'name' => $customer['name'],
                    'address' => 'Pelanggan data dummy Primadaya',
                    'notes' => 'Generated by BusinessDataSeeder',
                ]
            );
        }

        return Customer::all();
    }

    private function makeTransactionDate(int $sequence): Carbon
    {
        $baseDate = match (true) {
            $sequence <= 12 => Carbon::today(),
            $sequence <= 26 => Carbon::yesterday(),
            $sequence <= 38 => Carbon::today()->subDays(2),
            default => Carbon::today()->subDays(3),
        };

        return $baseDate
            ->copy()
            ->setTime(rand(8, 20), rand(0, 59), rand(0, 59));
    }

    private function createTransaction(
        User $user,
        Collection $services,
        Customer $customer,
        Collection $paperSizes,
        string $status,
        string $paymentStatus,
        Carbon $transactionDate,
        int $sequence
    ): void {
        $items = [];
        $subtotal = 0;

        foreach ($services as $service) {
            $item = $this->buildTransactionItem($service, $paperSizes);
            $items[] = $item;
            $subtotal += $item['subtotal'];
        }

        $discountPercent = rand(0, 100) <= 30 ? rand(5, 15) : 0;
        $discountAmount = $discountPercent > 0 ? round($subtotal * ($discountPercent / 100), 2) : 0;
        $total = max($subtotal - $discountAmount, 0);

        [$paymentMethod, $amountPaid, $dpAmount, $remainingAmount, $changeAmount] = $this->resolvePaymentData(
            paymentStatus: $paymentStatus,
            total: $total,
        );

        $transaction = Transaction::create([
            'uuid' => (string) Str::uuid(),
            'transaction_number' => sprintf(
                'TRX-%s-%04d-%s',
                $transactionDate->format('YmdHis'),
                $sequence,
                strtoupper(Str::random(3))
            ),
            'customer_id' => $customer->id,
            'user_id' => $user->id,
            'subtotal' => $subtotal,
            'discount_percent' => $discountPercent,
            'discount_amount' => $discountAmount,
            'total' => $total,
            'payment_method' => $paymentMethod,
            'amount_paid' => $amountPaid,
            'change_amount' => $changeAmount,
            'status' => $status,
            'payment_status' => $paymentStatus,
            'dp_amount' => $dpAmount,
            'remaining_amount' => $remainingAmount,
            'notes' => self::TRANSACTION_NOTE,
            'created_at' => $transactionDate,
            'updated_at' => $transactionDate,
        ]);

        foreach ($items as $item) {
            TransactionItem::create([
                ...$item,
                'transaction_id' => $transaction->id,
                'created_at' => $transactionDate,
                'updated_at' => $transactionDate,
            ]);
        }
    }

    private function buildTransactionItem(Service $service, Collection $paperSizes): array
    {
        $qty = rand(1, 12);
        $paperSizeId = null;
        $paperSizeName = null;
        $printType = 'na';
        $unitPrice = (float) ($service->base_price ?? 0);

        if ($service->has_matrix_pricing && $service->prices->isNotEmpty()) {
            $servicePrice = $service->prices->random();
            $paperSize = $servicePrice->paperSize ?? $paperSizes->get($servicePrice->paper_size_id);

            $paperSizeId = $paperSize?->id;
            $paperSizeName = $paperSize?->name;
            $printType = $servicePrice->print_type;
            $unitPrice = (float) $servicePrice->price;
            $qty = rand(5, 80);
        } elseif ($service->is_per_meter) {
            $qty = rand(1, 4);
        }

        $subtotal = $unitPrice * $qty;

        return [
            'service_id' => $service->id,
            'service_name' => $service->name,
            'paper_size_id' => $paperSizeId,
            'paper_size_name' => $paperSizeName,
            'print_type' => $printType,
            'qty' => $qty,
            'unit_price' => $unitPrice,
            'subtotal' => $subtotal,
            'item_notes' => 'Data dummy transaksi bisnis',
        ];
    }

    private function resolvePaymentData(string $paymentStatus, float $total): array
    {
        if ($paymentStatus === 'lunas') {
            $extraCash = rand(0, 1) === 1 ? rand(0, 5000) : 0;

            return [
                collect(['cash', 'transfer', 'qris'])->random(),
                $total + $extraCash,
                0,
                0,
                $extraCash,
            ];
        }

        if ($paymentStatus === 'dp') {
            $dpAmount = round($total * rand(35, 60) / 100, 2);

            return [
                collect(['cash', 'transfer', 'qris'])->random(),
                $dpAmount,
                $dpAmount,
                max($total - $dpAmount, 0),
                0,
            ];
        }

        return [
            'cash',
            0,
            0,
            $total,
            0,
        ];
    }

    private function seedMonthlyExpenses(User $cashier): void
    {
        $expenses = [
            ['category' => 'bahan', 'description' => 'Pembelian kertas HVS 80gr 10 rim', 'amount' => 780000],
            ['category' => 'bahan', 'description' => 'Pembelian tinta printer warna', 'amount' => 425000],
            ['category' => 'operasional', 'description' => 'Bayar listrik toko', 'amount' => 650000],
            ['category' => 'operasional', 'description' => 'Bayar internet bulanan', 'amount' => 385000],
            ['category' => 'gaji', 'description' => 'Gaji kasir mingguan', 'amount' => 900000],
            ['category' => 'operasional', 'description' => 'Servis printer laser', 'amount' => 350000],
            ['category' => 'bahan', 'description' => 'Pembelian plastik laminasi', 'amount' => 210000],
            ['category' => 'lainnya', 'description' => 'Konsumsi lembur tim produksi', 'amount' => 145000],
            ['category' => 'operasional', 'description' => 'Beli alat kebersihan toko', 'amount' => 120000],
            ['category' => 'bahan', 'description' => 'Pembelian spiral jilid', 'amount' => 175000],
            ['category' => 'lainnya', 'description' => 'Transport kirim pesanan customer', 'amount' => 95000],
            ['category' => 'operasional', 'description' => 'Perawatan mesin fotocopy', 'amount' => 560000],
        ];

        $smallExpenseTemplates = [
            ['category' => 'operasional', 'description' => 'Beli kopi untuk tim', 'min' => 12000, 'max' => 35000],
            ['category' => 'operasional', 'description' => 'Air mineral galon', 'min' => 18000, 'max' => 28000],
            ['category' => 'operasional', 'description' => 'Parkir operasional', 'min' => 3000, 'max' => 10000],
            ['category' => 'operasional', 'description' => 'Pulsa customer service', 'min' => 10000, 'max' => 25000],
            ['category' => 'bahan', 'description' => 'Beli lakban bening', 'min' => 8000, 'max' => 22000],
            ['category' => 'bahan', 'description' => 'Beli cutter dan isi pisau', 'min' => 10000, 'max' => 30000],
            ['category' => 'bahan', 'description' => 'Beli map plastik', 'min' => 5000, 'max' => 18000],
            ['category' => 'bahan', 'description' => 'Beli kertas cover', 'min' => 15000, 'max' => 45000],
            ['category' => 'lainnya', 'description' => 'Uang tip kurir lokal', 'min' => 5000, 'max' => 15000],
            ['category' => 'lainnya', 'description' => 'Jajan tamu toko', 'min' => 10000, 'max' => 30000],
        ];

        for ($i = 0; $i < 100; $i++) {
            $template = $smallExpenseTemplates[array_rand($smallExpenseTemplates)];

            $expenses[] = [
                'category' => $template['category'],
                'description' => $template['description'],
                'amount' => rand($template['min'], $template['max']),
            ];
        }

        foreach ($expenses as $index => $expense) {
            $expenseDate = Carbon::today()->subDays($index % 28);

            Expense::create([
                'user_id' => $cashier->id,
                'category' => $expense['category'],
                'description' => $expense['description'],
                'amount' => $expense['amount'],
                'expense_date' => $expenseDate,
                'notes' => self::EXPENSE_NOTE,
                'created_at' => $expenseDate->copy()->setTime(rand(9, 18), rand(0, 59)),
                'updated_at' => $expenseDate->copy()->setTime(rand(9, 18), rand(0, 59)),
            ]);
        }
    }
}
